name: build & Deploy Spring app

on:
  push:
    branches:
      -main

jobs:
  build-deploy:
    name: Build and Deploy Spring boot for beginner
    runs-on: ubuntu-latest
    steps:
    - name: Checkoout code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Unit Tests
      run: mvn -B test --file pom.xml
      name: build the application
      run:
        mvn clean
        mvn -B package --file pom.xml
