name: CICD
on: 
  push:
    branches : [main]
    
  pull_request: 
    branches : [main]
  
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.6

      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"
      - run: mysql -u root -e 'CREATE DATABASE employee_management_system'

      - name: All the Tests and Coverage check
        run: mvn clean install

  build-and-push-docker:
    needs: run-all-tests
    runs-on: ubuntu-latest
    steps:
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: adamidarrha/spring-boot
          tags: springBootImage
          registry: docker.io
          #dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
  deploy:
    needs: build-and-push-docker
    runs-on: springBootRunner # we are going to run it on ec2 instance
    steps:
      - name: pull image from docker hub
        run: docker pull adamidarrha/spring-boot:springBootImage  

      - name: delete old container
        run: docker rm -f springBootContainer
      
      - name: run docker container on ec2
        run: docker run -d -p 8080:8080 --name springBootContainer adamidarrha/spring-boot